spring.application.name=controleFinanceiro

spring.datasource.url=jdbc:postgresql://localhost:5432/controle_financeiro
spring.datasource.username=postgres
spring.datasource.password=matheuseduardo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.h2.console.enabled=true

